build-bininspect:
	g++ -o ./bininspect/bininspect ./bininspect/bininspect.cpp ./bininspect/BinaryInspector.cpp

build-studentdb:
	g++ -o ./studentdb/studentdb ./studentdb/studentdb.cpp ./studentdb/StudentDB.cpp ./studentdb/Exceptions.cpp

build-serde:
	g++ -o ./serde/serde ./serde/serde.cpp ./serde/Shape.cpp

build-executor:
	g++ -o ./executor/executor ./executor/executor.cpp ./executor/Tasks.cpp
